### ISSUE TITLE
Tag a production release of soar-null-router

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/secops-splunk-null-router#18]
Previously, all releases were pushed as `0.0.0` on any push. Now that production releases happen on tag (after closing #30), we should pick out the previously deployed last commit and tag it, so that the version in production is updated to have a version number. 

## Tasks

- [x] update as needed so that tagged versions deploy as their own tag - #28 should close this
- [x] #30
- [ ] Communicate with SecEng and CSOC, since while no change is expected, this is a production change (it will redeploy the same code.)
- [ ] tag and deploy version 1.0.0 (communicate with SecEng and CSOC on timing) at an appropriate deployment day and time (early in the week and early in the day)

**Comment by edthedev** [comment]
This was resolved by #30 and the following tag.
