### ISSUE TITLE
the block API option "autoscale" needs to be available to SOAR playbooks for the action "block"

### ISSUE THREAD

**Issue by gshere** [techservicesillinois/secops-splunk-null-router#21]
API doc: https://bhr-client.readthedocs.io/en/latest/api.html

The option "autoscale" for the api call for "block" needs to be available to SOAR playbooks for the SOAR action "block"

## Tasks

- [x] add a unit test that passes autoscale
- [x] add autoscale handler
- [ ] do a manual test passing the same IP twice, second time with shorter duration and autoscale=true, and see that the duration was set higher
