### ISSUE TITLE
Apply deployment fix

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-splunk-null-router#30]
See [template repo](https://github.com/techservicesillinois/splunk-soar-template/pull/19/files) for details.

## Tasks

- [x] apply changes to CI/CD `.yaml` file
- [x] apply changes to Makefile
- [x] apply changes to `app.json` file

**Comment by edthedev** [comment]
Changes are all made. Deployment is now failing due to an error trying to find bhr-client==1.6 on PyPI (from the SOAR service), which we cannot replicate locally on in our CI/CD.
