### ISSUE TITLE
Error when testing IP block on BHR in Splunk SOAR

### ISSUE THREAD

**Issue by tzturner** [techservicesillinois/secops-splunk-null-router#35]
## Context 

While working on #29 in the SOAR web interface I attempted to block an IPv6 address found in event [#68923](https://automate-illinois.soar.splunkcloud.com/mission/68923/analyst/action_run/183997) using `test_null_router` and received the following output:

```
Installation of pypi modules failed for app 949dc1bb-0ca3-404c-b698-d7d21d94eb94. Exception: Command '['/opt/phantom/bin/phenv', 'python3', '-m', 'pip', 'install', '--no-cache-dir', '--target', '/opt/phantom/apps/ncsabhr_949dc1bb-0ca3-404c-b698-d7d21d94eb94/dependencies', 'bhr-client==1.6']' returned non-zero exit status 1.

Output: Collecting bhr-client==1.6

  Downloading bhr_client-1.6-py3-none-any.whl (8.7 kB)

Collecting arrow==0.10.0

  Downloading arrow-0.10.0.tar.gz (86 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.5/86.5 kB 27.7 MB/s eta 0:00:00

  Preparing metadata (setup.py): started

  Preparing metadata (setup.py): finished with status 'error'

[notice] A new release of pip available: 22.1.2 -> 23.0.1

[notice] To update, run: pip3 install --upgrade pip

Error output: error: subprocess-exited-with-error

  

  × python setup.py egg_info did not run successfully.

  │ exit code: 1

  ╰─> [12 lines of output]

      /opt/phantom/usr/python39/lib/python3.9/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'zip_safe'

        warnings.warn(msg)

      /opt/phantom/usr/python39/lib/python3.9/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'install_requires'

        warnings.warn(msg)

      /opt/phantom/usr/python39/lib/python3.9/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'test_suite'

        warnings.warn(msg)

      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

         or: setup.py --help [cmd1 cmd2 ...]

         or: setup.py --help-commands

         or: setup.py cmd --help

      

      error: invalid command 'egg_info'

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed

× Encountered error while generating package metadata.

╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

hint: See above for details.
```

Steps to recreate:

- view the [BHR App on Splunk SOAR](https://automate-illinois.soar.splunkcloud.com/apps?search=bhr)
- click the eye symbol on the right-hand side
- on the right-hand side, click "Asset" to open a drop-down box
  - select `test_null_router`
- on the left, expand "Actions" > "Block"
- input the following:
  - cidr: 2405:201:11:d046:adaa:55c5:dcfa:9b80
  - source: SOAR
  - why: IPv6 NOCIDR test
  - duration: 60
  - autoscale: unchecked
- click "Test Action"

## Tasks

- [x] try this on our Midpoint app, which does not currently use PyPI packages.
- [x] continue work in Midpoint app to get better debug messages out https://github.com/techservicesillinois/secops-splunk-illinois-midpoint/pull/27
- [x] apply lessons learned about debug messaging from midpoint app here
- [x] apply lessons learned about debug messaging from midpoint app to our template repo (separate issue, but listing here as a reminder)
- [ ] new test for IPV6 address
- [ ] updates to pass test

**Comment by edthedev** [comment]
I'm guessing the error we got when trying to install is related:
https://github.com/techservicesillinois/secops-splunk-null-router/actions/runs/4441006175/jobs/7795526103?pr=34

**Comment by edthedev** [comment]
Relevant pull request: https://github.com/techservicesillinois/secops-splunk-null-router/pull/34

**Comment by tzturner** [comment]
Succeeded in recreating this error today, so there is still an issue here.

**Comment by edthedev** [comment]
This was closed by mistake while fixing various other issues.

**Comment by edthedev** [comment]
Got the first test `test_create_ticket` passing, by deleting the old cassette, updating to use vcr_cleaner, making some fixes, and re-recording. Probably need to do the same for the other cassettes to catch any changes in `tdxlib`.

**Comment by zdc217** [comment]
We tested blocking this IP address and it succeeded. We likely got past this while working out deployment issues. Closing this issue.
